### ISSUE TITLE
Integrate Proj4 into the app

### ISSUE THREAD

**Issue by marksmall** [edina/mapuse#2]
I had problems integrating **Proj4**, it is supposed to automatically register itself with **OpenLayers 3** but didn't. This could be to do with when libraries are loaded, but I really don't know. When I created a simple non-angular example following the [OpenLayers 3 Book](https://openlayersbook.github.io/ch07-wrapping-our-heads-around-projections/example-02.html) it just worked, but doing the same in the demo didn't.

**Comment by agxs** [comment]
If I debug the project, all the exports in `proj4` are placed in a `projt.defaults` object instead of at the root level for some reason. So eg, `proj4.defaults.def(...)` works.

However, Typescript won't let me do this because of the @types definition in the project. If I remove the `@types/proj4` typescript definition, then I can change the code to be the above and it works. Not sure why the exports are being loaded like this.
