### ISSUE TITLE
Publish/Subscribe System

### ISSUE THREAD

**Issue by marksmall** [edina/mapuse#6]
There will be a need for widgets to be able to **Publish** an event and for others to **Subscribe** to such events and act accordingly. An example would be **Annotations**, The **Draw Line** *interaction* (formally a control) should not be **active** when another *interaction* is **active**, therefore when a user selects a new *interaction*, all others should be **deactivated**.

It is unlikely this will be limited to just **Annotations**.

**Comment by agxs** [comment]
It would also be good to decouple components a bit more. For example, Search has a dependency on the MapService object. I think it would be better if the Search component created a SEARCH event instead of directly calling a method on the MapService, then something else can listen for that event and update the map.

**Comment by marksmall** [comment]
Services sounds the best approach, there are a number of examples of this:

* https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#bidirectional-service
* http://mean.expert/2016/05/21/angular-2-component-communication/ (search for **RXJS SUBJECT**)

**Comment by agxs** [comment]
Having discussed this we are going to implement a global event bus, similar to what we use in the existing Roam.
